{% set python_min = '3.10' %}
{% set name = "fastlite" %}
{% set version = "0.0.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastlite-{{ version }}.tar.gz
  sha256: e3039dd3ef144953691ea93ed902e46885a7d904feae92a11c835196693ad370

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - fastcore >=1.7.1
    - sqlite-minutils >=3.37.0.post4

test:
  imports:
    - fastlite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AnswerDotAI/fastlite
  summary: A bit of extra usability for sqlite
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
