{% set python_min = "3.10" %}
{% set name = "fastlite" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastlite-{{ version }}.tar.gz
  sha256: 58991844c6bf58ff266b32726b1456a58bb1225031ddc7e805c247c84d8a6b6c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - apswutils >=0.0.2
    - python >={{ python_min }}
    - fastcore >=1.7.1
    - sqlite-minutils >=3.37.0.post4

test:
  imports:
    - fastlite
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/AnswerDotAI/fastlite
  summary: A bit of extra usability for sqlite
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - synapticarbors
