schema_version: 1

context:
  python_min: '3.10'
  name: fastlite
  version: 0.2.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/fastlite-${{ version }}.tar.gz
  sha256: e98eb1d38de1f2dd1d62ff08ed174cc0a49fef30fd35cee543af890ce7d3e215

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools >=64.0
  run:
    - python >=${{ python_min }}
    - apswutils >=0.1.0
    - fastcore >=1.7.1
tests:
  - python:
      imports:
        - fastlite
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: A bit of extra usability for sqlite
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/AnswerDotAI/fastlite

extra:
  recipe-maintainers:
    - synapticarbors
